services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src/pages:/app/src/pages
      - ./styles:/app/styles
      - ./public:/app/public
      - ./src/components:/app/src/components