export type CharactersType ={
      Id: number,
      name: string,
      life: LifeProp,
      totalLife: number,
      safeguard: safeGuardProps[]
      lifeDice: string,
      createdBy: string
      surname?: string
      role: string
      desc: string
      age: string
      armor: number
      initiative: number
      displacement: string
      level?: number
      mainAtributes: MainAtributes[]
      skills: skillsType[]
      photo: ImageType
      // weapons: WeaponsType[]
      spells: SpellsType[]
      inventory?: ItemsType[]
}

export type SpellsProps ={
  Concentration: boolean,
    Description: string,
    Duration: string,
    Level: number,
    Material: string,
    Reach: string,
    Ritual: boolean,
    School: string,
    Somatic: true,
    SpellName: spellNameProps,
    Time: string,
    Verbal: boolean
}

export type LifeProp ={
  life: number
}

export type PreparedProp ={
  prepared: boolean
}

export type ItemsType ={
  id: number,
  name: string,
  description: string
}

export type MainAtributes = {
  name: string
  counter: number
  passive: number
}

export type WeaponsType={
  weaponType?: string,
  id: number,
  weaponName?: string,
  dice?: string
  cursed?: boolean,
}


export type IconType ={
    url: string,
    quantity: string
  }

export type LifeType = {
  totalLife: number,
  AtualLife: number,
  dice: string
}
  
export type SpellsType = {
    id: number,
    name: string,
    distance: '1,5 quilômetro' | 'Pessoal' | '150 metros' | '30 metros' | '18 metros' | '45 metros' |'3 metros' | '45 metros' | 'Toque' | '36 metros' | '9 metros' ,
    description: string,
    typeOfAttack: 'Spell' | 'Attack' 
    duration?: 'Instantânea'| '1 minuto' | '1 rodada' | '10 minutos' | '1 hora' | '24 horas' | '8 horas' ,
    schoolOfMagic?: string,
    cast?: '1 ação' | '1 reação' | '1 hora' | '1 minuto' | '1 ação bônus',
    rollAtack?: string,
    roolDamage?: string
    testToBeMade?: string,
    ritual?: boolean,
    superiorLevels?: string
    level?: number,
    prepared?: PreparedProp

    // arma
    weaponType?: string,
    dice?: string
    damageDice?: string
    cursed?: boolean,
  }
  export type InvocationType = {
    name: string,
    id: number
    description: string,
  }

  export type skillsType ={
    id: number;
    name: string,
    atribute: string;
    adder: number;
    proeficiency: boolean
  }

  export type ImageType ={
    url: string,
    desc?: string,
    id: number
  }

  export type safeGuardProps={
    id: number;
    name: string,
    adder: number;
    proeficiency: boolean
  }
  
  export type spellNameProps=
  [
    "ACALMAR EMOÇÕES",
    "ADIVINHAÇÃO",
    "AJUDA",
    "ALARME",
    "ALIADO PLANAR",
    "ALJAVA VELOZ",
    "ALTERAR FORMA",
    "ALTERAR-SE",
    "AMIZADE",
    "AMIZADE ANIMAL",
    "AMPLIAR PLANTAS",
    "ÂNCORA PLANAR",
    "ANDAR NA ÁGUA",
    "ANIMAR MORTOS",
    "ANIMAR OBJETOS",
    "ANTIPATIA/SIMPATIA",
    "APRIMORAR HABILIDADE",
    "APRISIONAMENTO",
    "ARCA SECRETA DE LEOMUND",
    "ÁREA ESCORREGADIA",
    "ARMA ELEMENTAL",
    "ARMA ESPIRITUAL",
    "ARMA MÁGICA",
    "ARMADURA ARCANA",
    "ARMADURA DE AGATHYS",
    "ARROMBAR",
    "ASSASSINO FANTASMAGÓRICO",
    "ATAQUE CERTEIRO",
    "ATAQUE VISUAL",
    "AUGÚRIO",
    "AUMENTAR/REDUZIR",
    "AURA DE PUREZA",
    "AURA DE VIDA",
    "AURA DE VITALIDADE",
    "AURA MÁGICA DE NYSTUL",
    "AURA SAGRADA",
    "AUXÍLIO DIVINO",
    "BANIMENTO",
    "BANQUETE DE HERÓIS",
    "BARREIRA DE LÂMINAS",
    "BÊNÇÃO",
    "BOCA ENCANTADA",
    "BOLA DE FOGO",
    "BOLA DE FOGO CONTROLÁVEL",
    "BOM FRUTO",
    "BORDÃO MÍSTICO",
    "BRAÇOS DE HADAR",
    "BRUXARIA",
    "CAMINHAR EM ÁRVORES",
    "CAMINHAR NO VENTO",
    "CAMPO ANTIMAGIA",
    "CÃO FIEL DE MORDENKAINEN",
    "CARNE PARA PEDRA",
    "CATIVAR",
    "CEGUEIRA/SURDEZ",
    "CHAMA CONTÍNUA",
    "CHAMA SAGRADA",
    "CHICOTE DE ESPINHOS",
    "CHUVA DE METEOROS",
    "CÍRCULO DA MORTE",
    "CÍRCULO DE PODER",
    "CÍRCULO DE TELETRANSPORTE",
    "CÍRCULO MÁGICO",
    "CLARIVIDÊNCIA",
    "CLONE",
    "COLUNA DE CHAMAS",
    "COMANDO",
    "COMPREENDER IDIOMAS",
    "COMPULSÃO",
    "COMUNHÃO",
    "COMUNHÃO COM A NATUREZA",
    "CONE DE FRIO",
    "CONFUSÃO",
    "CONHECIMENTO LENDÁRIO",
    "CONJURAR ANIMAIS",
    "CONJURAR CELESTIAL",
    "CONJURAR ELEMENTAIS MENORES",
    "CONJURAR ELEMENTAL",
    "CONJURAR FADA",
    "CONJURAR RAJADA",
    "CONJURAR SARAIVADA",
    "CONJURAR SERES DA FLORESTA",
    "CONSAGRAR",
    "CONSERTAR",
    "CONSTRIÇÃO",
    "CONTATO EXTRAPLANAR",
    "CONTINGÊNCIA",
    "CONTRAMÁGICA",
    "CONTROLAR A ÁGUA",
    "CONTROLAR O CLIMA",
    "CONVOCAR FAMILIAR",
    "CONVOCAR MONTARIA",
    "CONVOCAR RELÂMPAGOS",
    "CORDÃO DE FLECHAS",
    "COROA DA LOUCURA",
    "CORRENTE DE RELÂMPAGOS",
    "CRESCER ESPINHOS",
    "CRIAÇÃO",
    "CRIAR ALIMENTOS",
    "CRIAR CHAMAS",
    "CRIAR MORTOS-VIVOS",
    "CRIAR OU DESTRUIR ÁGUA",
    "CRIAR PASSAGEM",
    "CÚPULA ANTIVIDA",
    "CURA COMPLETA",
    "CURA COMPLETA EM MASSA",
    "CURAR FERIMENTOS",
    "CURAR FERIMENTOS EM MASSA",
    "DANÇA IRRESISTÍVEL DE OTTO",
    "DEDO DA MORTE",
    "DESEJO",
    "DESINTEGRAR",
    "DESPEDAÇAR",
    "DESPERTAR",
    "DESPISTAR",
    "DESTRUIÇÃO BANIDORA",
    "DESTRUIÇÃO CEGANTE",
    "DESTRUIÇÃO COLÉRICA",
    "DESTRUIÇÃO ESTONTEANTE",
    "DESTRUIÇÃO LANCINANTE",
    "DESTRUIÇÃO TROVEJANTE",
    "DETECTAR MAGIA",
    "DETECTAR O BEM E MAL",
    "DETECTAR PENSAMENTOS",
    "DETECTAR VENENO E DOENÇA",
    "DIFICULTAR DETECÇÃO",
    "DISCO FLUTUANTE DE TENSER",
    "DISFARÇAR-SE",
    "DISSIPAR MAGIA",
    "DISSIPAR O BEM E MAL",
    "DOENÇA PLENA",
    "DOMINAR BESTA",
    "DOMINAR MONSTRO",
    "DOMINAR PESSOA",
    "DRUIDISMO",
    "DUELO COMPELIDO",
    "ENCARNAÇÃO FANTASMAGÓRICA",
    "ENCONTRAR ARMADILHAS",
    "ENCONTRAR O CAMINHO",
    "ENFEITIÇAR PESSOA",
    "ENFRAQUECER INTELECTO",
    "ENVIAR MENSAGEM",
    "ESCRITA ILUSÓRIA",
    "ESCUDO ARCANO",
    "ESCUDO DA FÉ",
    "ESCUDO DE FOGO",
    "ESCURIDÃO",
    "ESFERA CONGELANTE DE OTILUKE",
    "ESFERA FLAMEJANTE",
    "ESFERA RESILIENTE DE OTILUKE",
    "ESPADA DE MORDENKAINEN",
    "GUARDIÕES ESPIRITUAIS",
    "ESPIRRO ÁCIDO",
    "ESQUENTAR METAL",
    "ESTABILIZAR",
    "EXPLOSÃO SOLAR",
    "FABRICAR",
    "FALAR COM ANIMAIS",
    "FALAR COM OS MORTOS",
    "FALAR COM PLANTAS",
    "FLECHA ÁCIDA DE MELF",
    "FLECHA RELAMPEJANTE",
    "FOGO DAS FADAS",
    "FOME DE HADAR",
    "FORÇA FANTASMAGÓRICA",
    "FORJAR MORTE",
    "FORMA ETÉREA",
    "FORMA GASOSA",
    "FORMAS ANIMAIS",
    "GLIFO DE VIGILÂNCIA",
    "GLOBO DE INVULNERABILIDADE",
    "GLOBOS DE LUZ",
    "GOLPE CONSTRITOR",
    "GUARDIÃO DA FÉ",
    "HEROÍSMO",
    "IDENTIFICAÇÃO",
    "IDIOMAS",
    "ILUSÃO MENOR",
    "ILUSÃO PROGRAMADA",
    "IMAGEM MAIOR",
    "IMAGEM SILENCIOSA",
    "IMOBILIZAR MONSTRO",
    "IMOBILIZAR PESSOA",
    "INFLIGIR FERIMENTOS",
    "INSETO GIGANTE",
    "INVERTER A GRAVIDADE",
    "INVISIBILIDADE",
    "INVISIBILIDADE MAIOR",
    "INVOCAÇÃO INSTANTÂNEA DE DRAWMIJ",
    "ISOLAMENTO",
    "LABIRINTO",
    "LÂMINA FLAMEJANTE",
    "LENTIDÃO",
    "LEQUE CROMÁTICO",
    "LEVITAÇÃO",
    "LIGAÇÃO TELEPÁTICA DE RARY",
    "LIMPAR A MENTE",
    "LOCALIZAR ANIMAIS OU PLANTAS",
    "LOCALIZAR CRIATURA",
    "LOCALIZAR OBJETO",
    "LOQUACIDADE",
    "LUFADA DE VENTO",
    "LUZ",
    "LUZ DO DIA",
    "MALOGRO",
    "MANSÃO MAGNÍFICA DE MORDENKAINEN",
    "MANTO DO CRUZADO",
    "MÃO DE BIGBY",
    "MÃOS FLAMEJANTES",
    "MÃOS MÁGICAS",
    "MARCA DA PUNIÇÃO",
    "MARCA DO CAÇADOR",
    "MEDO",
    "MENSAGEIRO ANIMAL",
    "MENSAGEM",
    "MESCLAR-SE ÀS ROCHAS",
    "METAMORFOSE",
    "METAMORFOSE VERDADEIRA",
    "MIRAGEM",
    "MISSÃO",
    "MÍSSEIS MÁGICOS",
    "MODIFICAR MEMÓRIA",
    "MOLDAR ROCHAS",
    "MONTARIA FANTASMAGÓRICA",
    "MOVER TERRA",
    "MOVIMENTAÇÃO LIVRE",
    "MURALHA DE ENERGIA",
    "MURALHA DE ESPINHOS",
    "MURALHA DE FOGO",
    "MURALHA DE GELO",
    "MURALHA DE PEDRA",
    "MURALHA DE VENTO",
    "MURALHA PRISMÁTICA",
    "NEVASCA",
    "NÉVOA FÉTIDA",
    "NÉVOA MORTAL",
    "NÉVOA OBSCURECENTE",
    "NUBLAR",
    "NUVEM DE ADAGAS",
    "NUVEM INCENDIÁRIA",
    "OLHO ARCANO",
    "ONDA DESTRUTIVA",
    "ONDA TROVEJANTE",
    "ORAÇÃO CURATIVA",
    "ORBE CROMÁTICA",
    "ORIENTAÇÃO",
    "PADRÃO HIPNÓTICO",
    "PALAVRA CURATIVA",
    "PALAVRA CURATIVA EM MASSA",
    "PALAVRA DE PODER ATORDOAR",
    "PALAVRA DE PODER CURAR",
    "PALAVRA DE PODER MATAR",
    "PALAVRA DE RECORDAÇÃO",
    "PALAVRA DIVINA",
    "PARAR O TEMPO",
    "PASSO NEBULOSO",
    "PASSOS LONGOS",
    "PASSOS SEM PEGADAS",
    "PATAS DE ARANHA",
    "PELE DE ÁRVORE",
    "PELE DE PEDRA",
    "PEQUENA CABANA DE LEOMUND",
    "PERDIÇÃO",
    "PISCAR",
    "PORTA DIMENSIONAL",
    "PORTAL",
    "PORTAL ARCANO",
    "PRAGA",
    "PRAGA DE INSETOS",
    "PRESTIDIGITAÇÃO",
    "PRISÃO DE ENERGIA",
    "PROIBIÇÃO",
    "PROJEÇÃO ASTRAL",
    "PROJETAR IMAGEM",
    "PROTEÇÃO CONTRA A MORTE",
    "PROTEÇÃO CONTRA ENERGIA",
    "PROTEÇÃO CONTRA LÂMINAS",
    "PROTEÇÃO CONTRA O BEM E MAL",
    "PROTEÇÃO CONTRA VENENO",
    "PROTEGER FORTALEZA",
    "PURIFICAR ALIMENTOS",
    "QUEDA SUAVE",
    "RAIO ADOECENTE",
    "RAIO ARDENTE",
    "RAIO DE BRUXA",
    "RAIO DE FOGO",
    "RAIO DE GELO",
    "RAIO DO ENFRAQUECIMENTO",
    "RAIO GUIADOR",
    "RAIO LUNAR",
    "RAIO SOLAR",
    "RAJADA DE VENENO",
    "RAJADA MÍSTICA",
    "RAJADA PRISMÁTICA",
    "RECIPIENTE ARCANO",
    "RECUO ACELERADO",
    "REENCARNAÇÃO",
    "REFLEXOS",
    "REGENERAÇÃO",
    "RELÂMPAGO",
    "REMOVER MALDIÇÃO",
    "REPOUSO TRANQUILO",
    "REPREENSÃO INFERNAL",
    "RESISTÊNCIA",
    "RESPIRAR NA ÁGUA",
    "RESSURREIÇÃO",
    "RESSURREIÇÃO VERDADEIRA",
    "RESTAURAÇÃO MAIOR",
    "RESTAURAÇÃO MENOR",
    "REVIVER OS MORTOS",
    "REVIVIFICAR",
    "RISO HISTÉRICO DE TASHA",
    "ROGAR MALDIÇÃO",
    "SALTO",
    "SANTUÁRIO",
    "SANTUÁRIO PARTICULAR DE MORDENKAINEN",
    "SARAIVADA DE ESPINHOS",
    "SEMIPLANO",
    "SENTIDO BESTIAL",
    "SERVO INVISÍVEL",
    "SEXTO SENTIDO",
    "SILÊNCIO",
    "SÍMBOLO",
    "SIMILARIDADE",
    "SIMULACRO",
    "SINAL DE ESPERANÇA",
    "SONHO",
    "SONO",
    "SUGESTÃO",
    "SUGESTÃO EM MASSA",
    "SUSSURROS DISSONANTES",
    "TAUMATURGIA",
    "TEIA",
    "TELECINÉSIA",
    "TELEPATIA",
    "TELETRANSPORTE",
    "TELETRANSPORTE POR ÁRVORES",
    "TEMPESTADE DA VINGANÇA",
    "TEMPESTADE DE FOGO",
    "TEMPESTADE DE GELO",
    "TENTÁCULOS NEGROS DE EVARD",
    "TERREMOTO",
    "TERRENO ALUCINÓGENO",
    "TOQUE ARREPIANTE",
    "TOQUE CHOCANTE",
    "TOQUE VAMPÍRICO",
    "TRANCA ARCANA",
    "TRUQUE DE CORDA",
    "TSUNAMI",
    "VELOCIDADE",
    "VER O INVISÍVEL",
    "VIAGEM PLANAR",
    "VIDÊNCIA",
    "VÍNCULO PROTETOR",
    "VINHA ESMAGADORA",
    "VISÃO DA VERDADE",
    "VISÃO NO ESCURO",
    "VIDA FALSA",
    "VOO",
    "ZOMBARIA VICIOSA",
    "ZONA DA VERDADE"
  ]