import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import CharacterCard from "~/components/CharacterCard";
import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

         
            <CharacterShow />
        </div>
      </main>
    </>
  );
}

function CharacterShow(){
  const { data: sessionData } = useSession();
  const  character = api.example.character.useQuery(
    undefined, // no input
    {
      enabled: sessionData?.user !== undefined,
    }
  );
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {character.isLoading ? <span>Loading...</span> :
        <CharacterCard 
          Character={character.data} 
          isError={character.isError} 
          isLoading={character.isLoading}
            
          />
      }
      </p>
    </div>
  );
}
